MBLBundle\Entity\Profil:
    type: entity
    table: fos_user
    repositoryClass: MBLBundle\Repository\ProfilRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            nullable: true
        prenom:
            type: string
            length: 255
            nullable: true
        description:
            type: text
            nullable: true
        linkedIn:
            type: string
            length: 255
            nullable: true
        localisation:
            type: string
            length: 255
            nullable: true
        lng:
            type: string
            length: 3
            nullable: true
        ville:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }


    manyToOne:
        etq:
            targetEntity: MBLBundle\Entity\ETQ
            inversedBy: profils

        dispo:
            targetEntity: MBLBundle\Entity\Dispo
            inversedBy: profils

        ou:
            targetEntity: MBLBundle\Entity\Ou
            inversedBy: profils

        metier:
            targetEntity: MBLBundle\Entity\Metier
            inversedBy: profils

        invest:
            targetEntity: MBLBundle\Entity\Invest
            inversedBy: profils



    manyToMany:
        competences:
            targetEntity: MBLBundle\Entity\Competences
            inversedBy: profils
        projets:
            targetEntity: MBLBundle\Entity\Projet
            inversedBy: profils
            cascade: ["persist"]
        chats:
            targetEntity: MBLBundle\Entity\Chat
            inversedBy: profils
            cascade: ["persist"]


    oneToOne:
        fichier:
            targetEntity: MBLBundle\Entity\Fichier
            cascade: ['all']